<a href="https://colab.research.google.com/github/ImShrekNotTanya/LB4_03_Prob_Theory/blob/Dev/LB4_03_Vakulenko_Adabeli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1:** Все примеры кода из статьи "Generating random number list in Python"



In [2]:
!git version

git version 2.34.1


In [3]:
!git config --global user.email “dinozavrik.tata@gmail.com”

!git config --global user.name “ImShrekNotTanya”

In [4]:
!git clone https://github.com/ImShrekNotTanya/LB4_03_Prob_Theory

Cloning into 'LB4_03_Prob_Theory'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 18 (delta 2), reused 17 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (18/18), done.
Resolving deltas: 100% (2/2), done.


In [5]:
%cd LB4_03_Prob_Theory

/content/LB4_03_Prob_Theory


In [6]:
!pwd

/content/LB4_03_Prob_Theory


In [7]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


In [8]:
!echo “# Some dummy text” >> new.md

In [9]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	new.md

nothing added to commit but untracked files present (use "git add" to track)


In [10]:
!git add

Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Turn this message off by running
hint: "git config advice.addEmptyPathspec false"


In [12]:
!git commit -m “committing from colab”

error: pathspec 'from' did not match any file(s) known to git
error: pathspec 'colab”' did not match any file(s) known to git


Method 1: Using the random.randint()

In [ ]:
import random

rand_list=[]
n=10
for i in range(n):
    rand_list.append(random.randint(3,9))
print(rand_list)

[4, 3, 8, 8, 9, 7, 8, 9, 9, 3]


Method 2: Using random.sample()

In [ ]:
import random

res = random.sample(range(1, 50), 7)
print ("Random number list is : " +  str(res))

Random number list is : [31, 34, 28, 49, 26, 10, 29]


Method 3: Using list comprehension + randrange()

In [ ]:
import random

res = [random.randrange(1, 50, 1) for i in range(7)]
print ("Random number list is : " +  str(res))

Random number list is : [33, 11, 8, 45, 4, 36, 21]


Method 4: using loop + randint()

In [ ]:
import random
lis = []
for _ in range(10):
    lis.append(random.randint(0, 51))
print(lis)

**Random Number Using Numpy**

Method 1: Generating a list of random integers using numpy.random.randint function

In [ ]:
import numpy as np

print(list(np.random.randint(low = 3,high=8,size=10)))
print(list(np.random.randint(low = 3,size=5)))

[6, 4, 6, 4, 7, 6, 4, 3, 3, 3]
[1, 0, 1, 0, 0]


Method 2. Generating a list of random floating values using numpy.random.random_sample function

In [ ]:
import numpy as np

print(np.random.random_sample(size = 4))

print(np.random.random_sample(size = (4,4)))

[0.31436562 0.64688359 0.11209488 0.8204064 ]
[[0.4339882  0.38768136 0.51866597 0.44536174]
 [0.08174387 0.54106231 0.30389867 0.34844988]
 [0.52264771 0.65474218 0.94040131 0.17612803]
 [0.04846221 0.44723945 0.82398934 0.28542303]]
