<a href="https://colab.research.google.com/github/ImShrekNotTanya/LB4_03_Prob_Theory/blob/master/LB4_03_Vakulenko_Adabeli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1:** Все примеры кода из статьи "Generating random number list in Python"



Method 1: Using the random.randint()

In [ ]:
import random

rand_list=[]
n=10
for i in range(n):
    rand_list.append(random.randint(3,9))
print(rand_list)

[4, 3, 8, 8, 9, 7, 8, 9, 9, 3]


Method 2: Using random.sample()

In [ ]:
import random

res = random.sample(range(1, 50), 7)
print ("Random number list is : " +  str(res))

Random number list is : [31, 34, 28, 49, 26, 10, 29]


Method 3: Using list comprehension + randrange()

In [ ]:
import random

res = [random.randrange(1, 50, 1) for i in range(7)]
print ("Random number list is : " +  str(res))

Random number list is : [33, 11, 8, 45, 4, 36, 21]


Method 4: using loop + randint()

In [ ]:
import random
lis = []
for _ in range(10):
    lis.append(random.randint(0, 51))
print(lis)

**Random Number Using Numpy**

Method 1: Generating a list of random integers using numpy.random.randint function

In [ ]:
import numpy as np

print(list(np.random.randint(low = 3,high=8,size=10)))
print(list(np.random.randint(low = 3,size=5)))

[6, 4, 6, 4, 7, 6, 4, 3, 3, 3]
[1, 0, 1, 0, 0]


Method 2. Generating a list of random floating values using numpy.random.random_sample function

In [ ]:
import numpy as np

print(np.random.random_sample(size = 4))

print(np.random.random_sample(size = (4,4)))

[0.31436562 0.64688359 0.11209488 0.8204064 ]
[[0.4339882  0.38768136 0.51866597 0.44536174]
 [0.08174387 0.54106231 0.30389867 0.34844988]
 [0.52264771 0.65474218 0.94040131 0.17612803]
 [0.04846221 0.44723945 0.82398934 0.28542303]]
